# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgsSAQEoATABOgIIIBISCAE4AUADSAFQHmgBwAYByAYB
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    disableTripleClick: true
    nodeInfoBroadcastSecs: 3600
    serialEnabled: true
  display:
    screenOnSecs: 600
  lora:
    configOkToMqtt: true
    hopLimit: 3
    ignoreMqtt: true
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: ENABLED
    gpsUpdateInterval: 10
    positionBroadcastSecs: 300
    positionFlags: 995
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:8InBFMMlOj9I7tMkTQb8C3ZDDYHANC3LfJA8OzB1E0I=
    publicKey: base64:mTovRNIgvaG03hEFpfJeSx4CXys4cAMufYUsAKX6QB4=
    serialEnabled: true
location:
  alt: 1060
  lat: 51.0774193
  lon: -114.0233708
module_config:
  ambientLighting:
    blue: 51
    current: 10
    green: 176
    red: 81
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  externalNotification:
    active: true
    alertMessage: true
    enabled: true
    nagTimeout: 60
    output: 24
    outputMs: 1000
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    mapReportingEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
  neighborInfo:
    updateInterval: 14400
  telemetry:
    airQualityInterval: 1800
    deviceUpdateInterval: 1800
    environmentUpdateInterval: 1800
owner: ROWLET-1
owner_short: "\U0001F388"

