# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgcSAQE6AgggEg8IATgBQANIAVAUaAHABgE
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    disableTripleClick: true
    nodeInfoBroadcastSecs: 3600
    serialEnabled: true
  display:
    screenOnSecs: 600
  lora:
    hopLimit: 3
    ignoreMqtt: true
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 20
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: ENABLED
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: true
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
module_config:
  ambientLighting:
    blue: 53
    current: 10
    green: 109
    red: 17
  detectionSensor:
    detectionTriggeredHigh: true
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
owner: KIRBY-3
owner_short: "\U0001F6F0"

