# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgcSAQE6AgggEg8IATgBQANIAVAKaAHABgE
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    disableTripleClick: true
    nodeInfoBroadcastSecs: 3600
    serialEnabled: true
  display:
    screenOnSecs: 600
  lora:
    hopLimit: 3
    ignoreMqtt: true
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 10
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: ENABLED
    gpsUpdateInterval: 10
    positionBroadcastSecs: 120
    positionBroadcastSmartEnabled: true
    positionFlags: 971
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
module_config:
  ambientLighting:
    blue: 51
    current: 10
    green: 176
    red: 81
  detectionSensor:
    detectionTriggeredHigh: true
    minimumBroadcastSecs: 45
  externalNotification:
    active: true
    alertMessage: true
    enabled: true
    nagTimeout: 60
    output: 24
    outputMs: 1000
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
  neighborInfo:
    updateInterval: 900
  telemetry:
    airQualityInterval: 900
    deviceUpdateInterval: 900
    environmentUpdateInterval: 900
owner: KIRBY-3
owner_short: "\U0001F6F0"

