[env:wio-e5-pico]
extends = stm32_base
board = lora_e5_dev_board
board_level = pr
board_upload.maximum_size = 233472 ; reserve the last 28KB for filesystem
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/stm32/wio-e5
  -DSERIAL_UART_INSTANCE=1
  -DPIN_SERIAL_RX=PB7
  -DPIN_SERIAL_TX=PB6
  -DPIN_WIRE_SDA=PA15
  -DPIN_WIRE_SCL=PB15
  -DHAS_SENSOR=1
  -DENABLE_HWSERIAL2
  -DPIN_SERIAL2_TX=PA2
  -DPIN_SERIAL2_RX=PA3
  -DHAS_GPS=1
  -DGPS_SERIAL_PORT=Serial2
  -DGPS_RX_PIN=PA3
  -DGPS_TX_PIN=PA2
  -DGPS_BAUDRATE=9600
  -DGNSS_MODEL=GNSS_MODEL_ATGM336H
# -DGPS_DEBUG_NMEA=1
  -DOVERRIDE_CH_UTIL=1 # for a tracker (bursting flight), send lots of data on a fixed private channel and never change the region via GPS. 
# -DDYNAMIC_REGION=1 # opposite for a pico balloon. 
upload_protocol = custom
upload_command = ${platformio.packages_dir}/tool-openocd/bin/openocd -f interface/cmsis-dap.cfg -f target/stm32wlx.cfg -c "adapter speed 1000" -c "transport select swd" -c "program {$SOURCE} 0x08000000 verify reset exit"
debug_tool = custom
debug_server = 
	${platformio.packages_dir}/tool-openocd/bin/openocd
	-f interface/cmsis-dap.cfg
	-f target/stm32wlx.cfg
	-c "transport select swd"
	-c "adapter speed 1000"
lib_deps =
  ${stm32_base.lib_deps}
  # Add your custom sensor here!