// #define RADIOLIB_CUSTOM_ARDUINO 1
// #define RADIOLIB_TONE_UNSUPPORTED 1
// #define RADIOLIB_SOFTWARE_SERIAL_UNSUPPORTED 1

#define ARDUINO_ARCH_AVR

#define EXT_NOTIFY_OUT -1
#define BUTTON_PIN -1

#define LED_PIN PIN_LED

#define BATTERY_SENSE_RESOLUTION_BITS ADC_RESOLUTION
#define BATTERY_PIN -1

#define GPS_DEBUG
#define RPI_PICO_WAVESHARE
#define HAS_GPS 1
#define PIN_GPS_EN 6
#define GPS_RX_PIN 9
#define GPS_TX_PIN 8
#define GPS_BAUDRATE 9600

#undef USE_SX126X
#define USE_RF95

#undef LORA_SCK
#undef LORA_MISO
#undef LORA_MOSI
#undef LORA_CS

#define LORA_SCK 10
#define LORA_MISO 12
#define LORA_MOSI 11
#define LORA_CS 3

#define LORA_RESET RADIOLIB_NC
#define LORA_DIO0 20
#define LORA_DIO1 RADIOLIB_NC
#define LORA_DIO2 2
