# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CioSIOX43Mh43pgzcD5-2Y3HwFUfRbjuEnxV8ZdYSRGRd1fEKAEwAToCCCASEQgBOAFAA0gBUB5YAWgByAYB
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    nodeInfoBroadcastSecs: 300
    role: TRACKER
    tzdef: MST7MDT,M3.2.0/2:00:00,M11.1.0/2:00:00
  display:
    screenOnSecs: 600
  lora:
    channelNum: 1
    configOkToMqtt: true
    hopLimit: 3
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: ENABLED
    gpsUpdateInterval: 30
    positionBroadcastSecs: 60
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:gC4/pH3RBs2F8tAKUoocTCGecLamVLcD+LzQvCfp2WE=
    publicKey: base64:MHmHrkuFTIJPzDhZdnUPKI4xu6MznNjoSHef92aShlo=
    serialEnabled: true
module_config:
  ambientLighting:
    blue: 57
    current: 10
    green: 122
    red: 48
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  externalNotification:
    active: true
    alertMessage: true
    enabled: true
    nagTimeout: 60
    output: 36
    outputMs: 1000
  mqtt:
    address: mqtt.meshtastic.org
    enabled: true
    encryptionEnabled: true
    mapReportSettings:
      positionPrecision: 14
      publishIntervalSecs: 3600
    mapReportingEnabled: true
    password: large4cats
    proxyToClientEnabled: true
    root: msh/US/AB
    username: meshdev
  telemetry:
    deviceUpdateInterval: 60
    environmentMeasurementEnabled: true
    environmentUpdateInterval: 60
    powerMeasurementEnabled: true
    powerUpdateInterval: 60
owner: VE6AZX-11
owner_short: AZX1

